class PopulatePlants < ActiveRecord::Migration
  def self.up
    [{ 
      :name => 'beans, bush', 
      :count => 180, 
      :yield => 68,
      :yield_unit => 'lbs.', 
      :hardiness => 'frost-sensitive', 
      :when_to_plant => 'On ADLF', 
      :seed => 'either', 
      :spacing => 4,
      :rows_per_bed => '2',
      :depth => '1',
      :feedings => '5',
    },
    { 
      :name => 'beans, pole', 
      :count => 180, 
      :yield => 92,
      :yield_unit => 'lbs.', 
      :hardiness => 'frost-sensitive', 
      :when_to_plant => 'On ADLF', 
      :seed => 'either', 
      :spacing => 4,
      :rows_per_bed => '1',
      :depth => '1',
      :feedings => '8-10',
    },
    { 
      :name => 'beets, red', 
      :count => 360, 
      :yield => 92,
      :yield_unit => 'lbs.', 
      :hardiness => 'moderately-hardy', 
      :when_to_plant => '2-3 weeks before', 
      :seed => 'either', 
      :spacing => 2,
      :rows_per_bed => '2',
      :depth => '0.5',
      :feedings => '5',
    },
    { 
      :name => 'berries, black & rasp.', 
      :count => 27, 
      :yield => 2.5,
      :yield_unit => 'gal.', 
      :hardiness => 'moderately-hardy', 
      :when_to_plant => '2-3 weeks before', 
      :seed => 'seedling', 
      :spacing => 14,
      :rows_per_bed => '1',
      :depth => '6',
      :feedings => '6',
    },
    { 
      :name => 'broccoli', 
      :count => 52, 
      :yield => 28,
      :yield_unit => 'lbs.', 
      :hardiness => 'hardy', 
      :when_to_plant => '4 weeks before', 
      :seed => 'seedling', 
      :spacing => 14,
      :rows_per_bed => '2 alt.*',
      :depth => '0.25',
      :feedings => '5',
    },
    { 
      :name => 'cabbage', 
      :count => 52, 
      :yield => 140,
      :yield_unit => 'lbs.', 
      :hardiness => 'hardy', 
      :when_to_plant => '4 weeks before', 
      :seed => 'seedling', 
      :spacing => 14,
      :rows_per_bed => '2 alt.',
      :depth => '0.25',
      :feedings => '5',
    },
    { 
      :name => 'carrots', 
      :count => 362, 
      :yield => 69,
      :yield_unit => 'lbs', 
      :hardiness => 'moderately-hardy', 
      :when_to_plant => '2-3 weeks before', 
      :seed => 'seed', 
      :spacing => 2,
      :rows_per_bed => '2',
      :depth => '0.125',
      :feedings => '6',
    },
    { 
      :name => 'cauliflower', 
      :count => 52, 
      :yield => 149,
      :yield_unit => 'lbs.', 
      :hardiness => 'hardy', 
      :when_to_plant => '4 weeks before', 
      :seed => 'seedling', 
      :spacing => 14,
      :rows_per_bed => '2 alt.',
      :depth => '0.25',
      :feedings => '5',
    },
    { 
      :name => 'celery', 
      :count => 62, 
      :yield => 150,
      :yield_unit => 'lbs.', 
      :hardiness => 'moderately-hardy', 
      :when_to_plant => '2-3 weeks before', 
      :seed => 'seedling', 
      :spacing => 12,
      :rows_per_bed => '2 alt.',
      :depth => '0 (don’t cover)',
      :feedings => '5',
    },
    { 
      :name => 'chard', 
      :count => 62, 
      :yield => 150,
      :yield_unit => 'lbs.', 
      :hardiness => 'moderately-hardy', 
      :when_to_plant => '2-3 weeks before', 
      :seed => 'either', 
      :spacing => 12,
      :rows_per_bed => '2 alt.',
      :depth => '0.25',
      :feedings => '4-6',
    },
    { 
      :name => 'corn', 
      :count => 92, 
      :yield => 92,
      :yield_unit => 'ears', 
      :hardiness => 'frost-sensitive', 
      :when_to_plant => 'On ADLF', 
      :seed => 'seed', 
      :spacing => 8,
      :rows_per_bed => '2 alt.',
      :depth => '0.5',
      :feedings => '5',
    },
    { 
      :name => 'cucumbers', 
      :count => 26, 
      :yield => 224,
      :yield_unit => 'lbs.', 
      :hardiness => 'frost-intolerant', 
      :when_to_plant => '2-3 weeks after', 
      :seed => 'seedling', 
      :spacing => 14,
      :rows_per_bed => '1',
      :depth => '0.25',
      :feedings => '8-12',
    },
    { 
      :name => 'kohlrabi', 
      :count => 240, 
      :yield => 120,
      :yield_unit => 'lbs.', 
      :hardiness => 'hardy', 
      :when_to_plant => '4 weeks before', 
      :seed => 'seedling', 
      :spacing => 3,
      :rows_per_bed => '2',
      :depth => '0.25',
      :feedings => '4',
    },
    { 
      :name => 'lettuce, head', 
      :count => 62, 
      :yield => 112,
      :yield_unit => 'lbs.', 
      :hardiness => 'hardy', 
      :when_to_plant => '4 weeks before', 
      :seed => 'either', 
      :spacing => 14,
      :rows_per_bed => '2 alt.',
      :depth => '0.125',
      :feedings => '4',
    },
    { 
      :name => 'lettuce, leaf', 
      :count => 122, 
      :yield => 30,
      :yield_unit => 'lbs.', 
      :hardiness => 'hardy', 
      :when_to_plant => '4 weeks before', 
      :seed => 'either', 
      :spacing => 6,
      :rows_per_bed => '2',
      :depth => '0.125',
      :feedings => '3',
    },
    { 
      :name => 'melons, cantaloupe', 
      :count => 26, 
      :yield => 182,
      :yield_unit => 'lbs.', 
      :hardiness => 'frost-intolerant', 
      :when_to_plant => '2-3 weeks after', 
      :seed => 'either', 
      :spacing => 14,
      :rows_per_bed => '1',
      :depth => '0.5',
      :feedings => '6-8',
    },
    { 
      :name => 'melons, honeydew', 
      :count => 26, 
      :yield => 182,
      :yield_unit => 'lbs.', 
      :hardiness => 'frost-intolerant', 
      :when_to_plant => '2-3 weeks after', 
      :seed => 'either', 
      :spacing => 14,
      :rows_per_bed => '1',
      :depth => '0.5',
      :feedings => '6-8',
    },
    { 
      :name => 'melons, watermelons', 
      :count => 26, 
      :yield => 182,
      :yield_unit => 'lbs.', 
      :hardiness => 'frost-intolerant', 
      :when_to_plant => '2-3 weeks after', 
      :seed => 'either', 
      :spacing => 14,
      :rows_per_bed => '1',
      :depth => '0.5',
      :feedings => '6-8',
    },
    { 
      :name => 'onions, green tops', 
      :count => 722, 
      :yield => 144,
      :yield_unit => 'bunches', 
      :hardiness => 'hardy', 
      :when_to_plant => '4 weeks before', 
      :seed => 'either', 
      :spacing => 1,
      :rows_per_bed => '2',
      :depth => '0.125',
      :feedings => '3',
    },
    { 
      :name => 'onions, large bulb', 
      :count => 722, 
      :yield => 135,
      :yield_unit => 'lbs.', 
      :hardiness => 'hardy', 
      :when_to_plant => '4 weeks before', 
      :seed => 'either', 
      :spacing => 1,
      :rows_per_bed => '2',
      :depth => '1.5',
      :feedings => '7',
    },
    { 
      :name => 'parsley', 
      :count => 92, 
      :yield => 23,
      :yield_unit => 'lbs.', 
      :hardiness => 'moderately-hardy', 
      :when_to_plant => '2-3 weeks before', 
      :seed => 'either', 
      :spacing => 8,
      :rows_per_bed => '2',
      :depth => '0.0625',
      :feedings => '5',
    },
    { 
      :name => 'parsnips', 
      :count => 240, 
      :yield => 175,
      :yield_unit => 'lbs.', 
      :hardiness => 'moderately-hardy', 
      :when_to_plant => '2-3 weeks before', 
      :seed => 'seed', 
      :spacing => 3,
      :rows_per_bed => '2',
      :depth => '0.5',
      :feedings => '7',
    },
    { 
      :name => 'peas, bush', 
      :count => 362, 
      :yield => 90,
      :yield_unit => 'lbs.', 
      :hardiness => 'hardy', 
      :when_to_plant => '4 weeks before', 
      :seed => 'either', 
      :spacing => 2,
      :rows_per_bed => '2',
      :depth => '0.75',
      :feedings => '4',
    },
    { 
      :name => 'peppers, all types', 
      :count => 62, 
      :yield => 320,
      :yield_unit => 'peppers', 
      :hardiness => 'frost-intolerant', 
      :when_to_plant => '2-3 weeks after', 
      :seed => 'seedling', 
      :spacing => 12,
      :rows_per_bed => '2 alt.',
      :depth => '0.5',
      :feedings => '6-8',
    },
    { 
      :name => 'potatoes', 
      :count => 92, 
      :yield => 145,
      :yield_unit => 'lbs.', 
      :hardiness => 'moderately-hardy', 
      :when_to_plant => '2-3 weeks before', 
      :seed => 'seed', 
      :spacing => 8,
      :rows_per_bed => '2 alt.',
      :depth => '1.5',
      :feedings => '4',
    },
    { 
      :name => 'radishes', 
      :count => 722, 
      :yield => 90,
      :yield_unit => 'bunches', 
      :hardiness => 'hardy', 
      :when_to_plant => '4 weeks before', 
      :seed => 'seed', 
      :spacing => 1,
      :rows_per_bed => '2',
      :depth => '0.125',
      :feedings => '2',
    },
    { 
      :name => 'spinach', 
      :count => 92, 
      :yield => 46,
      :yield_unit => 'lbs.', 
      :hardiness => 'hardy', 
      :when_to_plant => '4 weeks before', 
      :seed => 'seeding', 
      :spacing => 8,
      :rows_per_bed => '2 alt.',
      :depth => '0.25',
      :feedings => '4',
    },
    { 
      :name => 'squash, crooked-neck', 
      :count => 18, 
      :yield => 108,
      :yield_unit => 'lbs.', 
      :hardiness => 'frost-intolerant', 
      :when_to_plant => '2-3 weeks after', 
      :seed => 'either', 
      :spacing => 21,
      :rows_per_bed => '1',
      :depth => '0.75',
      :feedings => '5',
    },
    { 
      :name => 'squash, yellow', 
      :count => 18, 
      :yield => 108,
      :yield_unit => 'lbs.', 
      :hardiness => 'frost-intolerant', 
      :when_to_plant => '2-3 weeks after', 
      :seed => 'either', 
      :spacing => 21,
      :rows_per_bed => '1',
      :depth => '0.75',
      :feedings => '5',
    },
    { 
      :name => 'squash, zucchini', 
      :count => 18, 
      :yield => 108,
      :yield_unit => 'lbs.', 
      :hardiness => 'frost-intolerant', 
      :when_to_plant => '2-3 weeks after', 
      :seed => 'either', 
      :spacing => 21,
      :rows_per_bed => '1',
      :depth => '0.75',
      :feedings => '5',
    },
    { 
      :name => 'tomatoes', 
      :count => 26, 
      :yield => 156,
      :yield_unit => 'lbs.', 
      :hardiness => 'frost-sensitive', 
      :when_to_plant => 'On ADLF', 
      :seed => 'seedling', 
      :spacing => 14,
      :rows_per_bed => '1',
      :depth => '0.25',
      :feedings => '10-12',
    },
    { 
      :name => 'turnips', 
      :count => 180, 
      :yield => 46,
      :yield_unit => 'lbs.', 
      :hardiness => 'moderately-hardy', 
      :when_to_plant => '2-3 weeks before', 
      :seed => 'either', 
      :spacing => 2,
      :rows_per_bed => '2',
      :depth => '0.125',
      :feedings => '4',
    }].each do |p|
      Plant.create(p)
    end
  end

  def self.down
    Plant.destroy_all
  end
end
